# Generated by Django 2.2.7 on 2019-11-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(default='', max_length=20)),
                ('Time', models.CharField(default='', max_length=40)),
                ('Temperature', models.FloatField(default=0)),
                ('Humidity', models.FloatField(default=0)),
                ('Pressure', models.FloatField(default=0)),
                ('Soil', models.IntegerField(default=0)),
                ('ColorTemp', models.IntegerField(default=0)),
                ('Lux', models.FloatField(default=0)),
                ('RGB', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
