# Generated by Django 2.2.7 on 2019-12-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_plantdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('nickname', models.CharField(max_length=30)),
                ('deviceid', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
