# Generated by Django 2.2.7 on 2019-12-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_plant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='Plants',
        ),
    ]
