# Generated by Django 3.0.2 on 2020-02-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200201_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdata',
            old_name='deviceID',
            new_name='DeviceId',
        ),
        migrations.RenameField(
            model_name='plantdata',
            old_name='RaspID',
            new_name='SystemId',
        ),
    ]
