# Generated by Django 2.2.7 on 2020-02-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200201_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='Luminosity',
            field=models.IntegerField(default=0),
        ),
    ]
