# Generated by Django 3.0.2 on 2020-02-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200201_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='deviceid',
            field=models.CharField(max_length=30),
        ),
    ]
