# Generated by Django 3.0.2 on 2020-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200203_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='plant_pic',
            field=models.ImageField(blank=True, upload_to='plant_pics'),
        ),
    ]
