# Generated by Django 3.0.2 on 2020-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_plants_plant_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='deviceid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plants',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
