# Generated by Django 3.0.2 on 2020-02-03 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0016_auto_20200203_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('deviceid', models.CharField(max_length=20)),
                ('plant_pic', models.ImageField(blank=True, upload_to='plant_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
