# Generated by Django 3.0.2 on 2020-02-03 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0018_auto_20200203_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantstest',
            name='user',
            field=models.IntegerField(),
        ),
    ]
