# Generated by Django 3.0.2 on 2020-02-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20200203_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantsTest',
        ),
    ]
