# Generated by Django 3.0.2 on 2020-02-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_delete_plantstest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
