# Generated by Django 3.0.2 on 2020-02-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_ndvimeasurement_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='plant_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
