# Generated by Django 3.0.2 on 2020-02-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20200210_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='plant_pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
