# Generated by Django 3.0.2 on 2020-03-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20200210_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdata',
            name='NDVI_grade',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantdata',
            name='NDVI_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='White_pic',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plants',
            name='plant_type',
            field=models.CharField(choices=[('basil', 'Basil'), ('other', 'Other')], default='basil', max_length=20),
        ),
        migrations.AddField(
            model_name='plants',
            name='plantpot_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.DeleteModel(
            name='NDVIMeasurement',
        ),
    ]
