# Generated by Django 3.0.2 on 2020-03-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20200314_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='White_pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
