# Generated by Django 3.0.2 on 2020-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20200315_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='NDVI_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
