# Generated by Django 3.0.2 on 2020-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200315_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdata',
            name='Nir_pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='Segmentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='NDVI_value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
