# Generated by Django 3.0.2 on 2020-03-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20200315_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='NDVI_grade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True),
        ),
    ]
