# Generated by Django 3.0.2 on 2020-03-30 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20200331_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='MeasurementTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='ServerTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
