# Generated by Django 3.0.2 on 2020-03-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20200331_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdata',
            name='Segmentation',
        ),
    ]
