# Generated by Django 3.0.2 on 2020-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_remove_plantdata_segmentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdata',
            name='VPD',
            field=models.FloatField(default=0),
        ),
    ]
