# Generated by Django 3.0.2 on 2020-02-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature_pred', models.FloatField(default=0)),
                ('Luminosity_pred', models.FloatField(default=0)),
                ('SoilMoisture_pred', models.FloatField(default=0)),
                ('NDVI_pred', models.FloatField(default=0)),
            ],
        ),
    ]
