# Generated by Django 3.0.2 on 2020-02-29 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantprediction',
            name='DeviceID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 17, 58, 12, 506689)),
        ),
    ]
