# Generated by Django 2.2.7 on 2020-03-02 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_auto_20200229_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 22, 7, 56, 889581)),
        ),
    ]
