# Generated by Django 3.0.2 on 2020-03-14 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20200314_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 23, 28, 57, 540713)),
        ),
    ]
