# Generated by Django 3.0.2 on 2020-03-15 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_auto_20200315_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 13, 52, 58, 664424)),
        ),
    ]
