# Generated by Django 3.0.2 on 2020-03-15 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_auto_20200315_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 14, 3, 21, 445751)),
        ),
    ]
