# Generated by Django 3.0.2 on 2020-03-15 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20200315_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 19, 16, 47, 346594)),
        ),
    ]
