# Generated by Django 3.0.2 on 2020-03-31 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_auto_20200331_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 16, 19, 4, 215041)),
        ),
    ]
