# Generated by Django 3.0.2 on 2020-04-01 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_auto_20200331_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 20, 20, 29, 825238)),
        ),
    ]
