# Generated by Django 3.0.2 on 2020-04-02 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0015_auto_20200401_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 17, 11, 10, 335264)),
        ),
    ]
