# Generated by Django 3.0.2 on 2020-04-02 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_auto_20200402_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 23, 24, 29, 497339)),
        ),
    ]
