# Generated by Django 3.0.2 on 2020-04-03 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0017_auto_20200402_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 12, 54, 15, 602146)),
        ),
    ]
