# Generated by Django 3.0.2 on 2020-04-22 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0020_auto_20200421_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 14, 28, 56, 643749)),
        ),
    ]
