# Generated by Django 3.0.2 on 2020-04-27 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0021_auto_20200422_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 19, 49, 40, 745038)),
        ),
    ]
