# Generated by Django 3.0.2 on 2020-04-27 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0022_auto_20200427_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprediction',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 19, 50, 8, 418605)),
        ),
    ]
